// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiculeLocation.Backend.Data;

#nullable disable

namespace VehiculeLocation.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260113135527_betterVehicles")]
    partial class betterVehicles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateEnd = new DateTime(2025, 12, 13, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateEnd = new DateTime(2025, 12, 16, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateEnd = new DateTime(2025, 12, 12, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 12, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            VehicleId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateEnd = new DateTime(2025, 12, 20, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            DateStart = new DateTime(2025, 12, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 2,
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsAdmin = true,
                            Password = "$2a$12$.SP2dh9GQr/nVpFqTd.XGudDM/FkyBE8gKoXQmmTmE08tejW6SOb6",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            IsAdmin = false,
                            Password = "$2a$12$ztnvLsPVjDZ7dDq2y.K4seU6x47uk/CinTHGN.OaY3rwrSGpVqEDC",
                            Username = "Grigory Ivanovich Kulik"
                        });
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasColumnType("TEXT");

                    b.Property<float>("DailyRentalPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAutomaticTransmission")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Motorisation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Seats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Renault",
                            DailyRentalPrice = 30.5f,
                            Description = "Une voiture qui roule assez bien.",
                            ImagePath = "https://s3-eu-west-1.amazonaws.com/staticeu.izmocars.com/toolkit/commonassets/2024/24renault/24renaultcliotechnohb5rb/24renaultcliotechnohb5rb_animations/colorpix/fr/400x300/renault_24cliotechnohb5rb_orangevalencia_angular-front.webp",
                            IsAutomaticTransmission = false,
                            Model = "Clio V",
                            Motorisation = "Petrol",
                            Seats = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Peugeot",
                            DailyRentalPrice = 65f,
                            Description = "Une voiture qui roule vraiment bien, vous allez voir c'est top !",
                            ImagePath = "https://www.topgear.com/sites/default/files/2024/09/PEUGEOT_3008_EXT_13.jpg",
                            IsAutomaticTransmission = true,
                            Model = "3008",
                            Motorisation = "Diesel",
                            Seats = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Renault",
                            DailyRentalPrice = 25f,
                            Description = "Une voiture qui roule",
                            ImagePath = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/92/1997_Renault_Twingo_1.15_%281%29.jpg/330px-1997_Renault_Twingo_1.15_%281%29.jpg",
                            IsAutomaticTransmission = true,
                            Model = "Twingo",
                            Motorisation = "Electric",
                            Seats = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Citroën",
                            DailyRentalPrice = 35f,
                            Description = "Une voiture qui roule très bien",
                            ImagePath = "https://images.caradisiac.com/logos/5/8/1/4/135814/S8-Citroen-C-40397.jpg",
                            IsAutomaticTransmission = false,
                            Model = "C3",
                            Motorisation = "Petrol",
                            Seats = 5,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Rental", b =>
                {
                    b.HasOne("VehiculeLocation.Backend.Models.User", "User")
                        .WithMany("MyRentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehiculeLocation.Backend.Models.Vehicle", "Vehicle")
                        .WithMany("Rentals")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Vehicle", b =>
                {
                    b.HasOne("VehiculeLocation.Backend.Models.User", "User")
                        .WithMany("OwnedVehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.User", b =>
                {
                    b.Navigation("MyRentals");

                    b.Navigation("OwnedVehicles");
                });

            modelBuilder.Entity("VehiculeLocation.Backend.Models.Vehicle", b =>
                {
                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
